server {
    listen 80;
    server_name localhost;

    # آدرس صفحه وب
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # دریافت سابسکریپشن واقعی از سرویس پنل مرزبان روی شبکه داخلی ریلوی
    # نکته: اگر پورت پنل شما 8000 است از panel:8000 استفاده می‌شود
    location ~* ^/sub/(.*)$ {
        # بررسی اینکه آیا کاربر با نرم‌افزار VPN آمده یا مرورگر
        if ($http_user_agent ~* (v2ray|sing-box|streisand|shadowrocket|clash|flclash|nekobox|husi|happ)) {
            proxy_pass http://panel:8000/sub/$1$is_args$args;
        }

        # اگر کاربر با مرورگر آمده باشد، صفحه HTML باز می‌شود
        root /usr/share/nginx/html;
        try_files /index.html =404;
    }

    # API داخلی برای خواندن حجم و دیتای کاربر توسط کدهای جاوااسکریپت صفحه
    location ~* ^/api/sub-info/(.*)$ {
        proxy_pass http://panel:8000/sub/$1;
        proxy_set_header Host $host;
        proxy_set_header User-Agent "v2rayNG/1.8.12";
        proxy_pass_request_body off;
    }
}
