server {
    listen 80;
    server_name _;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    # تونل پروکسی به ورکر کلودفلر برای دریافت مستقیم هدرهای ترافیک بدون مسدودی مرورگر
    location /get-sub-data {
        proxy_pass https://late-truth-84b6.phoenix1198811.workers.dev/sub/djMsMSwxNzg5OTQ1NTEy.d1JmvrNN3xP-emhSxOLdoOJuU8YZnBCPZp5pTJm3EnI;
        proxy_ssl_server_name on;
        proxy_set_header Host late-truth-84b6.phoenix1198811.workers.dev;
        proxy_set_header User-Agent "v2rayNG/1.8.12";
        
        # آزادسازی هدرها برای جاوااسکریپت
        add_header Access-Control-Allow-Origin * always;
        add_header Access-Control-Expose-Headers "Subscription-Userinfo, content-disposition, *" always;
    }
}
