server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # دریافت ایمن اطلاعات ساب بدون خطای CORS
    location /get-sub-data {
        proxy_pass https://late-truth-84b6.phoenix1198811.workers.dev/sub/djMsMSwxNzg5OTQ1NTEy.d1JmvrNN3xP-emhSxOLdoOJuU8YZnBCPZp5pTJm3EnI;
        proxy_ssl_server_name on;
        proxy_hide_header Access-Control-Allow-Origin;
        proxy_hide_header Access-Control-Expose-Headers;
        add_header Access-Control-Allow-Origin * always;
        add_header Access-Control-Expose-Headers "Subscription-Userinfo, *" always;
    }
}
