server {
    listen 80;
    listen [::]:80;
    server_name _;

    resolver 1.1.1.1 8.8.8.8 valid=300s;
    resolver_timeout 5s;

    location ~* ^/sub/(.*) {
        # اگر نرم‌افزار وی‌پی‌ان بود
        if ($http_user_agent ~* (v2ray|v2rayng|sing-box|hiddify|clash|nekobox|streisand|shadowrocket|foxray)) {
            proxy_pass https://panel.jetserves.xyz:2096/sub/$1$is_args$args;
            break;
        }

        # ارسال درخواست پنهانی برای خواندن اطلاعات کاربر با اضافه کردن مجوز هدرها
        add_header Access-Control-Allow-Origin * always;
        add_header Access-Control-Expose-Headers "subscription-userinfo" always;

        root /usr/share/nginx/html;
        try_files /index.html =404;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
