server {
    listen 80;
    listen [::]:80;
    server_name _;

    resolver 1.1.1.1 8.8.8.8 valid=300s;
    resolver_timeout 5s;

    # مسیر دریافت داده‌های ترافیک توسط جاوااسکریپت
    location ~* ^/get-info/(.*) {
        proxy_pass https://panel.jetserves.xyz:2096/sub/$1$is_args$args;
        proxy_ssl_server_name on;
        proxy_set_header Host panel.jetserves.xyz;
        proxy_set_header User-Agent "ClashforWindows/0.20.39";

        add_header Access-Control-Allow-Origin * always;
        add_header Access-Control-Expose-Headers "subscription-userinfo" always;
    }

    # مسیر اصلی سابسکریپشن
    location ~* ^/sub/(.*) {
        # اگر کاربر نرم‌افزار وی‌پی‌ان بود، کانفیگ خام تحویل داده شود
        if ($http_user_agent ~* (v2ray|v2rayng|sing-box|hiddify|clash|nekobox|streisand|shadowrocket|foxray)) {
            proxy_pass https://panel.jetserves.xyz:2096/sub/$1$is_args$args;
            proxy_ssl_server_name on;
            break;
        }

        # اگر در مرورگر باز شد، قالب باز شود
        root /usr/share/nginx/html;
        try_files /index.html =404;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
