server {
    listen 80;
    server_name localhost;

    # وقتی کاربر با مرورگر لینک سابسکریپشن را باز می‌کند، قالب نمایش داده شود
    location ~* ^/sub/ {
        # اگر درخواست از سمت کلاینت‌های وی‌پی‌ان بود، مستقیم به پاسارگاد وصل شود
        if ($http_user_agent ~* (v2ray|v2rayng|sing-box|hiddify|clash|nekobox|streisand|shadowrocket)) {
            proxy_pass https://panel.jetserves.xyz:2096;
            break;
        }

        # اگر کاربر در مرورگر باز کرد، داشبورد HTML باز شود
        root /usr/share/nginx/html;
        try_files /index.html =404;
    }

    # برای بقیه مسیرها و صفحه اصلی
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}
